import { Metadata } from "next";
import React from "react";
import styles from "../styles";
import Image from "next/image";
import SabahCenterSection from "@/components/SabahCenterSection";
import ContactUSection from "@/components/ContactUSection";

export const metadata: Metadata = {
    title: "دكتور علاء الدين ابو شادي",
    description: "Generated by create next app",
};

const SabahCenter = () => {
    return (
        <>
            {/* hero section */}
            <SabahCenterSection />

            {/* about section */}
            <div
                className={`${styles.boxWidth} flex flex-col justify-between items-center h-full mx-auto w-full gap-8 mt-24`}>
                <h2 className="text-green-600 text-2xl md:text-3xl font-bold">
                    من هو د/ علاء الدين ابو شادي
                </h2>
                <p className="text-center md:text-right text-lg md:text-xl text-black  font-normal">
                    لوريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية
                    هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور
                    النشر. كان لوريم إيبسوم. لوريم إيبسوم(Lorem Ipsum) هو ببساطة
                    نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في
                    صناعات المطابع ودور النشر. كان لوريم إيبسوم. لوريم
                    إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي
                    الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر.
                    كان لوريم إيبسوم.
                </p>
            </div>

            <div
                className={`${styles.boxWidth} grid grid-cols-1 md:grid-cols-2 h-full mx-auto w-full gap-8 mt-24`}>
                <div className="flex w-full h-[595px] mx-auto">
                    <Image
                        className="object-cover rounded-xl"
                        src="/images/sabah1.jpeg"
                        alt="Dr Alaa"
                        width={595}
                        height={100}
                    />
                </div>
                <div className="flex w-full h-[595px] mx-auto">
                    <Image
                        className="object-cover rounded-xl"
                        src="/images/sabah2.jpeg"
                        alt="Dr Alaa"
                        width={595}
                        height={100}
                    />
                </div>
                <div className="flex w-full h-[595px] mx-auto">
                    <Image
                        className="object-cover rounded-xl"
                        src="/images/sabah3.jpeg"
                        alt="Dr Alaa"
                        width={595}
                        height={100}
                    />
                </div>
                <div className="flex w-full h-[595px] mx-auto">
                    <Image
                        className="object-cover rounded-xl"
                        src="/images/sabah4.jpeg"
                        alt="Dr Alaa"
                        width={595}
                        height={100}
                    />
                </div>
                <div className="flex w-full h-[595px] mx-auto">
                    <Image
                        className="object-cover rounded-xl"
                        src="/images/sabah5.jpeg"
                        alt="Dr Alaa"
                        width={595}
                        height={100}
                    />
                </div>
                <div className="flex w-full h-[595px] mx-auto">
                    <Image
                        className="object-cover rounded-xl"
                        src="/images/sabah6.jpeg"
                        alt="Dr Alaa"
                        width={595}
                        height={100}
                    />
                </div>
            </div>

            <ContactUSection />
        </>
    );
};

export default SabahCenter;
