import HeroSection from "@/components/HeroSection";
import AboutSection from "@/components/AboutSection";
import OurProductsSection from "@/components/OurProductsSection";
import ServicesSection from "@/components/ServicesSection";
import SabahCenterSection from "@/components/SabahCenterSection";
import ContactUSection from "@/components/ContactUSection";
import Footer from "@/components/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "مركز شادي للطب البديل",
    description: "Generated by create next app",
};

export default function Home() {
    return (
        <>
            {/* Hero Section */}
            <HeroSection />

            {/* About Section */}
            <AboutSection />

            {/* Our Products Section */}
            <OurProductsSection />

            {/* Services Section */}
            <ServicesSection />

            {/* Sabah Center Section */}
            <SabahCenterSection />

            {/* Contact Us section */}
            <ContactUSection />
        </>
    );
}
